### ISSUE TITLE
Don't reverse geocode. 

### ISSUE THREAD

**Issue by geohacker** [mapbox/osrm-frontend-v2#8]
It would be ideal to preserve the coordinates supplied by the user for routing. Currently, we send the coordinates to Nominatim to get an address through reverse geocoding. Here are the options I'm seeing:
- Remove geocoding altogether. 
- Set a URL flag and don't geocode

cc @batpad @srividyacb @freenerd @shvrm

**Comment by batpad** [comment]
@geohacker not sure this is required? Since there is no issue when you navigate to a lat-lng via URL. I think all we want is something like "do not attempt to geocode strings that look like lat-lngs". Can we close this and maybe make a separate issue / feature request for that? And that seems like maybe a useful feature to have in upstream as well.

**Comment by geohacker** [comment]
Yeah :+1:
